#!/bin/sh

### Get os name via uname
_myos="$(uname)"

# Aliases
alias -- -='cd -'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias j='autojump'
alias br='hr "*"'
alias bc='bc -l '
alias c='clear'
alias df='df -h'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias h='history'
alias mkdir='mkdir -p'
alias myip='curl ifconfig.me'
alias q='exit'
alias screen='echo Use tmux you dolt'
alias su='sudo -i'
alias root='sudo -i'
alias h='history'
alias j='jobs -l'
alias mount='mount |column -t'
alias sha1='openssl sha1'
alias diff='colordiff'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'

### Add safetry nets
# confirmation
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
# Parenting changing perms on /
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

### System memory related
## pass options to free
alias meminfo='free -m -l -t'
## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
## get top process eating cpu
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
## Get server cpu info
alias cpuinfo='lscpu'
## older system use /proc/cpuinfo
alias cpuinfo='less /proc/cpuinfo'
## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'


### Network alias
# Stop after sending count ECHO_REQUEST packets #
alias ping='ping -c 5'
# Do not wait interval 1 second, go fast #
alias fastping='ping -c 100 -s.2'
# Show open ports
alias ports='netstat -tulanp'

### Control firewall
## shortcut  for iptables and pass it via sudo#
alias ipt='sudo /sbin/iptables'
# display all rules #
alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers'
alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
alias iptlistfw='sudo /sbin/iptables -L FORWARD -n -v --line-numbers'
alias firewall=iptlist

### tmux alias
alias tmux='tmux -2'

### vim alias
alias vi='vim'
alias svi='sudo vi'
alias edit='vim'
alias vimupdate='vim +PlugUpgrade +PlugUpdate +qall'

### if user is not root, pass all commands via sudo #
if [ $UID -ne 0 ]; then
    alias reboot='sudo reboot'
fi

### add alias as per os using $_myos
case $_myos in
   Linux)
      alias la='\ls --color=auto -F -T 0 -A'
      alias ll='\ls --color=auto -F -T 0 -la'
      alias ls='ls --color=auto -F -T 0'
      alias l.='ls -d .* --color=auto'
      alias apt-get='sudo apt-get'
      ### Add safetry nets
      # do not delete / or prompt if deleting more than 3 files at a time
      alias rm='rm -I --preserve-root'
      if [ $UID -ne 0 ]; then
         alias update='sudo apt-get update'
         alias upgrade='sudo apt-get upgrade'
      fi
      ;;
   Darwin)
      alias foo='/path/to/sunos/bin/foo' ;;
   FreeBSD|OpenBSD)
      alias foo='/path/to/bsd/bin/foo' ;;
   SunOS)
      alias foo='/path/to/sunos/bin/foo' ;;
   *) ;;
esac

extract()
{
 if [ -z "$1" ]; then
    # display usage if no parameters given
    echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
    echo "       extract <path/file_name_1.ext> [path/file_name_2.ext] [path/file_name_3.ext]"
    return 1
 else
    for n in $@
    do
      if [ -f "$n" ] ; then
          case "${n%,}" in
            *.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
                         tar xvf "$n"       ;;
            *.lzma)      unlzma ./"$n"      ;;
            *.bz2)       bunzip2 ./"$n"     ;;
            *.rar)       unrar x -ad ./"$n" ;;
            *.gz)        gunzip ./"$n"      ;;
            *.zip)       unzip ./"$n"       ;;
            *.z)         uncompress ./"$n"  ;;
            *.7z|*.arj|*.cab|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.rpm|*.udf|*.wim|*.xar)
                         7z x ./"$n"        ;;
            *.xz)        unxz ./"$n"        ;;
            *.exe)       cabextract ./"$n"  ;;
            *)
                         echo "extract: '$n' - unknown archive method"
                         return 1
                         ;;
          esac
      else
          echo "'$n' - file does not exist"
          return 1
      fi
    done
fi
}
