#!/bin/sh

DEFAULT_DIR=.
SEARCH_PATH=${1:-$DEFAULT_DIR}

for d in $(find $SEARCH_PATH -type d -name .git); do
    git_path=$(dirname $d)
    (
        cd ${git_path}
        echo ${git_path}:
        git status --short
        echo
    )
done
