#!/bin/bash

# Make sure that arguments are expanded to string
ARGS="$@"
if [ -z "$ARGS" ]; then
    echo "Usage: git who [REV-RANGE] FILE..."
    exit 0
fi

git rev-parse $1 -- >/dev/null 2>&1
if [ $? -ne 0 ]; then
    REVISIONS="`git rev-list --max-parents=0 HEAD`.."
else
    REVISIONS=$1
    shift
fi

git log --pretty="%ae" $REVISIONS -- $@ | sort -u
