#!/bin/sh

OS="$(uname)"
DOT_FILES_REPO=`git rev-parse --show-toplevel`
HOME_DIR=$DOT_FILES_REPO/home
SCRIPT_DIR=$HOME_DIR/.scripts
MY_ENV=$SCRIPT_DIR/my_env
PC_SETUP_DIR=$SCRIPT_DIR/pc-setup
COMMON_SCRIPT_DIR=$PC_SETUP_DIR/common
LINUX_SCRIPT_DIR=$PC_SETUP_DIR/linux
OSX_SCRIPT_DIR=$PC_SETUP_DIR/osx

do_not_install_package()
{
    echo "This package is nots suppported!"
    exit 0;
}
