#!/bin/sh

### Export build env
. ../../../../build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y update
        sudo apt-get -y upgrade ;;
    "remove")
        echo "Nothing to remove";;
    (*)
        exit -1;
esac

exit 0;

