#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y install git git-core;;
    "remove")
	### Do not remove git as we use that for build_env
        # sudo apt-get -y remove git git-core;;
	;;
    (*)
        exit -1;
esac

exit 0;

