#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y install openssh-server;;
    "remove")
        sudo apt-get -y remove openssh-server;;
    (*)
        exit -1;
esac

exit 0;

