#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo add-apt-repository -y ppa:jonathonf/vim
        sudo apt-get update -y
        sudo apt-get -y install vim
        sudo pip3 install grip ;;
    "remove")
        sudo apt-get -y remove vim
        sudo rm -rf ~/.viminfo ;;
    (*)
        exit -1;
esac

exit 0;

