#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y install vim ;;
    "remove")
        sudo apt-get -y remove vim ;;
    (*)
        exit -1;
esac

exit 0;

