#!/bin/sh

CMD="$1"

case $CMD in
    "install")
        sudo apt-get update
        sudo apt-get install python3-dev python3-pip
        sudo pip3 install thefuck
        ;;
    "remove")
        sudo apt-get remove python3-dev python3-pip
        sudo pip3 uninstall thefuck
        ;;
    (*)
        exit -1;
esac

exit 0;

