#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y update
        sudo apt-get -y install python-dev python-pip
        pip install --upgrade pip
        sudo pip install thefuck
        echo "eval \$(thefuck --alias)" >> $MY_ENV;;
    "remove")
        sudo apt-get -y remove python-dev python-pip
        sudo pip uninstall thefuck
        ;;
    (*)
        exit -1;
esac

exit 0;

