#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y update
        sudo apt-get -y install python3-dev python3-pip
        sudo pip3 install thefuck
        ;;
    "remove")
        sudo apt-get -y remove python3-dev python3-pip
        sudo pip3 uninstall thefuck
        ;;
    (*)
        exit -1;
esac

exit 0;

