#!/bin/sh

### Export build env
. ../../../../build_env

CMD="$1"
ACK_BIN=$DOT_FILES_REPO/home/.scripts/ack

case $CMD in
    "install")
        ### https://beyondgrep.com/install/
        curl https://beyondgrep.com/ack-2.18-single-file > $ACK_BIN
        chmod +x $ACK_BIN;;
    "remove")
        sudo rm -rf $HIGHLIGHTER_BIN;;
    (*)
        exit -1;
esac

exit 0;

