#!/bin/sh

CMD="$1"

case $CMD in
    "install"i)
        ### https://github.com/AlDanial/cloc
        sudo apt-get install cloc;;
    "remove")
        sudo apt-get remove cloc;;
    (*)
        exit -1;
esac

exit 0;

