#!/bin/sh

### Export build env
. ../../../../build_env

CMD="$1"

case $CMD in
    "install")
        ### https://github.com/AlDanial/cloc
        sudo apt-get -y install cloc;;
    "remove")
        sudo apt-get -y remove cloc;;
    (*)
        exit -1;
esac

exit 0;

