#!/bin/sh

### Export build env
. ./build_env

CMD="$1"
POWERLINE_FONTS_REPO=$SCRIPT_DIR/fonts
NERD_FONT_REPO=$SCRIPT_DIR/nerd-fonts

case $CMD in
    "install")
        pip3 install powerline-status
        pip3 install --user git+git://github.com/powerline/powerline
        git clone --recursive https://github.com/powerline/fonts.git $POWERLINE_FONTS_REPO
        cd $POWERLINE_FONTS_REPO
        ./install.sh
        cd -
        rm -rf $POWERLINE_FONTS_REPO

        wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
        wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
        sudo mv $DOT_FILES_REPO/PowerlineSymbols.otf ~/.local/share/fonts/
        fc-cache -vf ~/.local/share/fonts/
        mkdir -p ~/.config/fontconfig/conf.d/
        mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/;

        git clone --recursive https://github.com/ryanoasis/nerd-fonts $NERD_FONT_REPO
        cd $NERD_FONT_REPO
        ./install.sh
        cd -
        rm -rf $NERD_FONT_REPO;;
    "remove")
        ;;
    (*)
        exit -1;
esac

exit 0;

