#!/bin/sh

### Export build env
. ./build_env

CMD="$1"
TMUX_POWERLINE_REPO=$HOME_DIR/.tmux-powerline
TPM_REPO=$HOME_DIR/.tmux/plugins/tpm

case $CMD in
    "install")
        sudo apt-get install -y libevent-dev
        git clone https://github.com/tmux/tmux /tmp/tmux
        cd /tmp/tmux
        sh autogen.sh
        ./configure
        make all
        sudo make install

        rm -rf $TMUX_POWERLINE_REPO
        git clone https://github.com/erikw/tmux-powerline.git $TMUX_POWERLINE_REPO
        git clone https://github.com/tmux-plugins/tpm $TPM_REPO;;
    "remove")
        sudo rm -rf /tmp/tmux
        sudo rm -rf $HOME_DIR/.tmux-powerline;;
    (*)
        exit -1;
esac

exit 0;

