#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update -y
        sudo apt-get install -y google-chrome-stable;;
    "remove")
        sudo apt-get remove -y google-chrome-stable;;
    (*)
        exit -1;
esac

exit 0;


