#!/bin/sh

CMD="$1"

case $CMD in
    "install")
        ### https://github.com/robbyrussell/oh-my-zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    "remove")
        echo "Operation not supported!";;
    (*)
        exit -1;
esac

exit 0;

