#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        ### https://github.com/robbyrussell/oh-my-zsh
        sudo apt-get -y install zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" ;;
    "remove")
        yes | sh ~/.oh-my-zsh/tools/uninstall.sh
        sudo apt-get -y remove zsh
	sudo rm -rf ~/.zcompdump* ~/.zsh_history ~/.zsh-update ~/.z ;;
    (*)
        exit -1;
esac

exit 0;

