#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y install build-essential
        sudo apt-get -y install automake
        sudo apt-get -y install cmake
        sudo apt-get -y install ninja-build
        sudo apt-get -y install curl
        sudo apt-get -y install libncurses5-dev libncursesw5-dev
        sudo apt-get -y install libncurses5-dev:i386
        sudo apt-get -y install openjdk-7-jdk
        sudo apt-get -y install libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386
        sudo apt-get -y install g++-multilib mingw32 tofrodos
        sudo apt-get -y install python-markdown zlib1g-dev:i386
        sudo apt-get -y install lzop
        sudo apt-get -y install lm-sensors hddtemp
        sudo apt-get -y install xdotool
        # Needed by https://github.com/JamshedVesuna/vim-markdown-preview
        pip3 install --user grip;;
    "remove")
        sudo apt-get -y remove build-essential
        sudo apt-get -y remove automake
        sudo apt-get -y remove cmake
        sudo apt-get -y remove ninja-build
        sudo apt-get -y remove curl
        sudo apt-get -y remove libncurses5-dev libncursesw5-dev
        sudo apt-get -y remove lm-sensors hddtemp;;
    (*)
        exit -1;
esac

exit 0;

