#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        ### hub-core
        sudo pip install pyyaml

        ### Hubv2-os
        sudo apt-get install -y device-tree-compiler

        ### Updater
        sudo apt-get install -y ansible;;
    "remove")
        ### hub-core
        sudo pip remove -y pyyaml

        ### Hubv2-os
        sudo apt-get remove -y device-tree-compiler

        ### Updater
        sudo apt-get remove -y ansible;;
    (*)
        exit -1;
esac

exit 0;

