#!/bin/sh

### Export build env
. ./build_env

CMD="$1"
GO_PACKAGE=go1.8.3.linux-amd64.tar.gz
GO_REPO=$SCRIPT_DIR

case $CMD in
    "install")
        ### https://golang.org/doc/install
        ### https://tecadmin.net/install-go-on-ubuntu/#
        sudo apt-get -y update
        sudo apt-get -y upgrade
        wget https://storage.googleapis.com/golang/$GO_PACKAGE -O /tmp/$GO_PACKAGE
        tar -xvf /tmp/$GO_PACKAGE -C $GO_REPO
        rm -rf /tmp/$GO_PACKAGE
        sudo mv $GO_REPO/go /usr/local
        echo "export PATH=\$PATH:/usr/local/go/bin" >> $TEMP_BUILD_ENV;;
    "remove")
        sudo rm -rf /usr/local/go;;
    (*)
        exit -1;
esac

exit 0;

