#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        curl https://sh.rustup.rs -sSf | bash -s -- -y
        . ~/.cargo/env
        rustup self update
        rustup update
        rustup install stable
        rustup target add armv7-unknown-linux-gnueabihf
        rustup target add aarch64-linux-android
        rustup target add arm-unknown-linux-gnueabi;;
    "remove")
        rustup self uninstall -y;;
    (*)
        exit -1;
esac

exit 0;

