#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        sudo apt-get -y install unity-tweak-tool

        sudo -A add-apt-repository ppa:numix/ppa -y
        sudo apt-get -y update
        sudo apt-get -y install numix-gtk-theme numix-icon-theme-circle numix-wallpaper-* ;;
    "remove")
        sudo apt-get -y remove unity-tweak-tools
        sudo apt-get -y remove numix-gtk-theme numix-icon-theme-circle numix-wallpaper-* ;;
    (*)
        exit -1;
esac

exit 0;

