#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        ### https://github.com/nogizhopaboroda/iponmap
        sudo npm install -g iponmap;;
    "remove")
        sudo npm uninstall iponmap;;
    (*)
        exit -1;
esac

exit 0;

