#!/bin/sh

CMD="$1"
DOT_FILES_REPO=`git rev-parse --show-toplevel`
PIPES_BIN=$DOT_FILES_REPO/home/.scripts/pipes

case $CMD in
    "install")
        ### https://github.com/pipeseroni/pipes.sh
        sudo curl https://github.com/pipeseroni/pipes.sh > $PIPES_BIN
        cmod +x $PIPES_BIN;;
    "remove")
        sudo rm -rf $PIPES_BIN;;
    (*)
        exit -1;
esac

exit 0;

