#!/bin/sh

### Export build env
. ../../../../build_env

CMD="$1"
PIPES_BIN=$DOT_FILES_REPO/home/.scripts/pipes

case $CMD in
    "install")
        ### https://github.com/pipeseroni/pipes.sh
        sudo curl https://raw.githubusercontent.com/pipeseroni/pipes.sh/master/pipes.sh > $PIPES_BIN
        chmod +x $PIPES_BIN;;

    "remove")
        sudo rm -rf $PIPES_BIN;;
    (*)
        exit -1;
esac

exit 0;

