#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        ### http://termsaver.brunobraga.net/
        sudo apt-get -y install termsaver;;
    "remove")
        sudo apt-get -y remove termsaver;;
    (*)
        exit -1;
esac

exit 0;

