#!/bin/sh

### Export build env
. ../../../../build_env

CMD="$1"
ACQUARIUM_BIN=$DOT_FILES_REPO/home/.scripts/acquarium
ACQUARIUM_REPO=$DOT_FILES_REPO/home/.scripts/acquarium-repo

case $CMD in
    "install")
        ### https://www.cyberciti.biz/tips/linux-unix-apple-osx-terminal-ascii-aquarium.html 
        OLD_DIR=`pwd`
        sudo apt-get -y install libcurses-perl

        mkdir -p $ACQUARIUM_REPO
        cd $ACQUARIUM_REPO
        wget http://search.cpan.org/CPAN/authors/id/K/KB/KBAUCOM/Term-Animation-2.4.tar.gz
        tar -zxvf Term-Animation-2.4.tar.gz
        cd Term-Animation-2.4/
        perl Makefile.PL && make && make test
        sudo make install

        cd $ACQUARIUM_REPO
        wget http://www.robobunny.com/projects/asciiquarium/asciiquarium.tar.gz
        tar -zxvf asciiquarium.tar.gz
        cd asciiquarium_1.1/
        cp asciiquarium $ACQUARIUM_BIN
        chmod +x $ACQUARIUM_BIN

        rm -rf $ACQUARIUM_REPO
        cd $OLD_DIR
        ;;
    "remove")
        sudo rm -rf $ACQUARIUM_BIN
    (*)
        exit -1;
esac

exit 0;

