#!/bin/sh

CMD="$1"

case $CMD in
    "install")
        sudo apt-get install conky conky-all
        sudo apt-add-repository -y ppa:teejee2008/ppa
        sudo apt update
        sudo apt install conky-manager;;
    "remove")
        sudo apt-get remove conky conky-all
        sudo apt remove conky-manager;;
    (*)
        exit -1;
esac

exit 0;

