#!/bin/sh

### Export build env
. ./build_env

CMD="$1"
CONKY_THEMES_REPO=$SCRIPT_DIR/conky-themes

case $CMD in
    "install")
        AUREOLA_THEME_REPO=$CONKY_THEMES_REPO/Aureola
        git clone https://github.com/erikdubois/Aureola $AUREOLA_THEME_REPO
        yes | $AUREOLA_THEME_REPO/get-aureola-from-github-to-local-drive-v1.sh
        sudo rm -rf $CONKY_THEMES_REPO


        ### https://github.com/akshendra/Serene-Conky
        ## TODO INSTALL THIS ONE AWESOME
        ## TAKE BACKUP OF EXISTING ONE ~/.config/conky

        ### Install and run default conky-theme
        OLD_DIR=`pwd`
        cd ~/.aureola/gambodekuno
        ./install-conky.sh
        sudo rm -rf ~/.aureola
        cd $OLD_DIR
        git checkout $HOME_DIR/.config/conky
        echo "Install this fonts: https://fonts2u.com/knife-fight-ballet-regular.font"
        read;;
    "remove")
        sudo rm -rf ~/.aureola;;
    (*)
        exit -1;
esac

exit 0;

