#!/bin/sh

### Export build env
. ./build_env

CMD="$1"

install_symlinks()
{
    ### Take backup of factory configuration
    mv ~/.bashrc ~/.bashrc.org
    ln -fs $HOME_DIR/.bashrc ~/.bashrc

    mv ~/.bash_profile ~/.bash_profile.org
    ln -fs $HOME_DIR/.bash_profile ~/.bash_profile

    mv ~/Pictures ~/Pictures.org
    ln -fs $HOME_DIR/Pictures ~/Pictures

    mv ~/.config ~/.config.org
    ln -fs $HOME_DIR/.config ~/.config
    cp ~/.config.org/* ~/.config/. -rf

    ln -fs $HOME_DIR/.Xresources ~/.Xresources
    ln -fs $HOME_DIR/.bash-completion ~/.bash-completion
    ln -fs $HOME_DIR/.bash_logout ~/.bash_logout
    ln -fs $HOME_DIR/.dir_colors ~/.dir_colors
    ln -fs $HOME_DIR/.fluxbox ~/.fluxbox
    ln -fs $HOME_DIR/.gitconfig ~/.gitconfig
    ln -fs $HOME_DIR/.gitignore_global ~/.gitignore_global
    ln -fs $HOME_DIR/.inputrc ~/.inputrc
    ln -fs $HOME_DIR/.tmux ~/.tmux
    ln -fs $HOME_DIR/.tmux/tmux.conf ~/.tmux.conf
    ln -fs $HOME_DIR/.tmux/tmux.conf.local ~/.tmux.conf.local
    ln -fs $HOME_DIR/.tmux-powerline ~/.tmux-powerline
    ln -fs $HOME_DIR/.vim ~/.vim
    ln -fs $HOME_DIR/.vim/vimrc ~/.vimrc
    ln -fs $HOME_DIR/.ideavimrc ~/.ideavimrc
    ln -fs $HOME_DIR/.vim_undo ~/.vim_undo
    ln -fs $HOME_DIR/.xinitrc ~/.xinitrc
    ln -fs $HOME_DIR/.zsh ~/.zsh
    ln -fs $HOME_DIR/.zsh_logout ~/.zsh_logout
    ln -fs $HOME_DIR/.zshrc ~/.zshrc
    ln -fs $HOME_DIR/.ssh ~/.ssh
    ln -fs $HOME_DIR/.wegorc ~/.wegorc
    ln -fs $SCRIPT_DIR ~/.scripts
}

remove_symlinks()
{
    rm -rf ~/Pictures
    rm -rf ~/.Xresources
    rm -rf ~/.bash-completion
    rm -rf ~/.bash_logout
    rm -rf ~/.bash_profile
    rm -rf ~/.bashrc
    rm -rf ~/.config
    rm -rf ~/.dir_colors
    rm -rf ~/.fluxbox
    rm -rf ~/.gitconfig
    rm -rf ~/.gitignore_global
    rm -rf ~/.vimrc
    rm -rf ~/.ideavimrc
    rm -rf ~/.inputrc
    rm -rf ~/.scripts
    rm -rf ~/.tmux.conf
    rm -rf ~/.vim
    rm -rf ~/.vim_undo
    rm -rf ~/.xinitrc
    rm -rf ~/.zsh
    rm -rf ~/.zshrc
    rm -rf ~/.ssh
    rm -rf ~/.wegorc
}

# Entry point for script
case $CMD in
    "install"|"remove")
        ${CMD}_symlinks;;
    (*)
        exit -1;
esac

exit 0;

