#!/bin/sh


### NOTE: This should be the last script to execute

### Export build env
. ./build_env

CMD="$1"

case $CMD in
    "install")
        ;;
    "remove")
        mv ~/.bash_profile.org ~/.bash_profile
        mv ~/.bashrc.org ~/.bashrc
        mv ~/Pictures.org ~/Pictures
    (*)
        exit -1;;
esac

### Print success banner
sync && cat $SCRIPT_DIR/banner

while true; do
    read -p "It is recommended to reboot the PC to take changes in effect, Do you wish to reboot now(y/n)?" yn
    case $yn in
        [Yy]* )
            echo "Rebooting..."
            sudo reboot
            break;;
        [Nn]* )
            gnome-terminal
            break;;
        * ) echo "Please answer yes or no.";;
    esac
done

exit 0;

