#!/bin/sh

### NOTE: This should be the last script to execute

### Export build env
. ./build_env

CMD="$1"

### Print success banner
cat $SCRIPT_DIR/banner;
echo "Press any key to start new terminal session..."
echo; echo
echo "It is advisable to close this and use new session."

read dummy

case $CMD in
    "install")
        ;;
    "remove")
        mv ~/.bash_profile.org ~/.bash_profile
        mv ~/.bashrc.org ~/.bashrc
        mv ~/Pictures.org ~/Pictures
        sync;;
    (*)
        exit -1;;
esac

gnome-terminal

exit 0;

